"""second time Change column name from response to questions

Revision ID: 3cb6b4d8fd87
Revises: cca10921cb6c
Create Date: 2026-02-24 13:53:13.117673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb6b4d8fd87'
down_revision: Union[str, Sequence[str], None] = 'cca10921cb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'response', new_column_name='questions')    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'questions', new_column_name='response')    # ### end Alembic commands ###
