"""Initial Migration

Revision ID: 96b49eb92775
Revises: 
Create Date: 2026-02-24 13:10:56.169725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96b49eb92775'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.alter_column('questions', 'topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('questions', 'no_of_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'llm_message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('questions', 'total_marks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'minimum_marks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'marks_scored',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.alter_column('questions', 'marks_scored',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('questions', 'minimum_marks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'total_marks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'llm_message',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('questions', 'no_of_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'topic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('questions', 'response',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
