from pydantic import BaseModel
from typing import Dict, Any, Optional, List

class QuestionMetaData(BaseModel):
    topic: str
    no_of_questions: int
    message: Optional[str] = None
    total_marks: int
    minimum_marks: int

class QuestionDetail(BaseModel):
    question: str
    options: Dict[str, str]
    correct_answer: Dict[str, str]
    marks: int

class SaveQuestionRequest(BaseModel):
    # id generated by db

    questions: Dict[str, QuestionDetail]
    metadata: QuestionMetaData

    model_config = {
        "from_attributes": True, 
        "json_schema_extra": {
            "example": {
                "questions": {
                    "q1": {
                        "question": "What is the capital of France?",
                        "options": {"a": "Paris", "b": "London"},
                        "correct_answer": {"a": "Paris"},
                        "marks": 5
                    }
                },
                "metadata": {
                    "topic": "Geography",
                    "no_of_questions": 1,
                    "message": "Success",
                    "total_marks": 5,
                    "minimum_marks": 2
                }
            }
        }
    }

class SaveQuestionResponse(SaveQuestionRequest):
    id: int

class SaveQuestionListResponse(BaseModel):
    items: List[SaveQuestionResponse]

